"""Slide deck generation constants."""

from __future__ import annotations

import re

MIN_SLIDES = 5
MAX_SLIDES = 12
MAX_CONTEXT_CHARS = 42000
BATCH_CONTEXT_CHARS = 6000
MAX_DECK_ATTEMPTS = 3
MAX_DECK_OUTPUT_TOKENS = 18000
MAX_WORDS_PER_BULLET = 20
MAX_BULLETS_PER_SLIDE = 4
SLIDE_WIDTH = 1600
SLIDE_HEIGHT = 900
PDF_RENDER_SCALE = 2
FLOW_ACTION_MAX_WORDS = 16
CARD_DESC_MAX_WORDS = 24
CARD_POINT_MAX_WORDS = 14
CARD_MAX_POINTS = 3
CALLOUT_MAX_WORDS = 32
MAX_SOURCE_CROPS_PER_DECK = 6
MIN_CROP_CONFIDENCE = 0.58
SOURCE_VISUAL_PROMOTION_THRESHOLD = 3
LEGACY_LAYOUTS = {
    "TITLE",
    "KEY_BULLETS",
    "TWO_COLUMNS",
    "THREE_FEATURES",
    "BIG_STAT",
    "FIGURE_FOCUS",
    "SECTION_DIVIDER",
    "HIGHLIGHT_CARD",
    "TIMELINE",
}
COMPONENT_LAYOUTS = {
    "TITLE_HERO",
    "DUAL_PILLARS",
    "GRID_COMPOSITE",
    "PROCESS_FLOW_WITH_CALLOUT",
    "VISUAL_ANCHOR",
    "METRIC_DASHBOARD",
    "CODE_COMPARISON",
    "CHECKLIST",
    "PROCESS_TIMELINE",
    "COMPARISON_TABLE",
    "ICON_GRID",
    "TRANSITION",
}
VISUAL_LAYOUTS = {"TITLE_HERO", "VISUAL_ANCHOR"}
DENSE_LAYOUTS = {
    "GRID_COMPOSITE",
    "PROCESS_FLOW_WITH_CALLOUT",
    "METRIC_DASHBOARD",
    "CODE_COMPARISON",
    "CHECKLIST",
    "PROCESS_TIMELINE",
    "COMPARISON_TABLE",
    "ICON_GRID",
}
MEDIUM_DENSITY_LAYOUTS = {"DUAL_PILLARS", "VISUAL_ANCHOR"}
ICON_KEYS = {
    "cpu",
    "globe",
    "gauge",
    "database",
    "layers",
    "box",
    "route",
    "workflow",
    "warning",
    "check",
    "rocket",
    "zap",
    "code",
    "palette",
    "gamepad",
    "package",
    "server",
    "shield",
    "search",
    "list-checks",
    "repeat",
    "timer",
    "network",
    "activity",
    "braces",
    "bug",
    "boxes",
    "file-json",
    "git-branch",
    "hard-drive",
    "image",
    "languages",
    "lightbulb",
    "memory-stick",
    "mouse-pointer-click",
    "table",
    "wrench",
}
ICON_LABELS = {
    "cpu": "CPU",
    "globe": "GLB",
    "gauge": "SPD",
    "database": "DB",
    "layers": "LYR",
    "box": "BOX",
    "route": "RTE",
    "workflow": "WF",
    "warning": "!",
    "check": "OK",
    "rocket": "GO",
    "zap": "ZAP",
    "code": "</>",
    "palette": "ART",
    "gamepad": "PAD",
    "package": "PKG",
    "server": "SRV",
    "shield": "SEC",
    "search": "SRC",
    "list-checks": "CHK",
    "repeat": "LOOP",
    "timer": "TIME",
    "network": "NET",
    "activity": "ACT",
    "braces": "{}",
    "bug": "BUG",
    "boxes": "BOX",
    "file-json": "JSON",
    "git-branch": "GIT",
    "hard-drive": "DISK",
    "image": "IMG",
    "languages": "LANG",
    "lightbulb": "IDEA",
    "memory-stick": "MEM",
    "mouse-pointer-click": "UI",
    "table": "TBL",
    "wrench": "TOOL",
}
DANGLING_TRAILING_WORDS = {
    "and",
    "or",
    "to",
    "with",
    "via",
    "through",
    "by",
    "for",
    "in",
    "on",
    "of",
    "tang",
    "giam",
    "va",
    "hoac",
    "de",
    "bang",
    "qua",
    "voi",
    "khi",
    "khong",
    "con",
    "nhung",
    "co",
    "the",
    "gay",
}
SOURCE_VISUAL_STOPWORDS = {
    "and",
    "the",
    "for",
    "with",
    "from",
    "this",
    "that",
    "page",
    "slide",
    "image",
    "figure",
    "description",
    "trong",
    "cua",
    "voi",
    "cho",
    "cac",
    "mot",
    "nhung",
    "duoc",
    "khong",
    "hinh",
    "anh",
    "trang",
    "mota",
}
FINAL_SUMMARY_TITLES = {
    "tom tat",
    "tong ket",
    "ket luan",
    "summary",
    "recap",
    "conclusion",
    "takeaways",
    "key takeaways",
}
GENERIC_SLIDE_TITLES = {
    "overview",
    "introduction",
    "main idea",
    "key points",
    "content",
    "topic",
    "slide",
    "details",
    "presentation",
    "academic overview from selected sources",
    "tong quan",
    "tong quan hoc thuat",
    "tong quan hoc thuat tu nguon da chon",
    "gioi thieu",
    "noi dung",
    "y chinh",
    "chu de",
}
COVERAGE_TOPIC_RULES: dict[str, tuple[str, ...]] = {
    "Localization Methods": (
        "hardcode",
        "dictionary",
        "json",
        "localization package",
        "string table",
        "asset table",
        "localization table",
    ),
    "Runtime Localization Flow": (
        "game start",
        "localizationsettings",
        "selectedlocale",
        "table database",
        "localized string event",
        "lazy load",
    ),
    "Smart Strings": (
        "smart string",
        "smartformat",
        "playername",
        "plural",
        "choose",
        "variable",
    ),
    "Pseudo Localization": (
        "pseudo localization",
        "hardcode",
        "font",
        "encoding",
        "double byte",
        "ui layout",
    ),
    "Localization Architecture": (
        "namespace",
        "string table collection",
        "addressables",
        "lazy load",
        "asset table collection",
        "production",
    ),
    "Profiler Diagnostics": (
        "profiler",
        "diagnostics",
        "gc alloc",
        "timeline",
        "camera render",
        "frame",
        "ms",
    ),
    "Garbage Collector": (
        "garbage collector",
        "mark phase",
        "sweep phase",
        "managed heap",
        "gc roots",
        "heap",
    ),
    "Object Pooling": (
        "object pooling",
        "objectpool",
        "pool",
        "bullet",
        "projectile",
        "fx",
        "instantiate",
    ),
    "Physics Optimization": (
        "physics",
        "fixed timestep",
        "collision matrix",
        "collider",
        "raycast",
        "layermask",
    ),
    "Rendering And UI Optimization": (
        "gpu",
        "rendering",
        "occlusion culling",
        "texture atlas",
        "rectmask2d",
        "lighting",
        "bake light",
    ),
    "Memory And Asset Management": (
        "memory",
        "assetbundle",
        "asset bundle",
        "addressables",
        "shader",
        "scene",
        "leak",
        "ram",
        "texture",
        "audio",
        "mesh",
    ),
}
ALLOWED_LAYOUTS = COMPONENT_LAYOUTS
CITATION_PATTERN = re.compile(r"\[(?:\d+(?:\s*,\s*\d+)*)\]")
